contentLayer: relu4_3
contentPath: src/data/content.jpg
contentWeight: 475.71
height: 400
initImage: Content
iterations: 10
learning_rate: 0.01
model: VGG16
optimizer: Adam
reconstruct: Content
reprSavFreq: 1
stylePath: src/data/style.jpg
styleWeight: 307.7
totalVariationWeight: 854.25
type: Transfer
visualize: 'Yes'
